QUESTION_POOL_SEED = [{'description': 'Variables, control flow, and Python best practices.',
  'difficulty_pools': {'easy': [{'answer': 'def',
                                 'options': ['func', 'define', 'def', 'lambda'],
                                 'question': 'Which keyword defines a function in Python?'},
                                {'answer': 'print()',
                                 'options': ['echo()', 'print()', 'say()', 'log()'],
                                 'question': 'Which function prints to the console?'},
                                {'answer': '#',
                                 'options': ['//', '#', '--', '/*'],
                                 'question': 'Which symbol starts a comment?'},
                                {'answer': 'str',
                                 'options': ['int', 'float', 'str', 'bool'],
                                 'question': 'What data type does input() return?'}],
                       'hard': [{'answer': 'Positional argument tuple',
                                 'options': ['Keyword arguments',
                                             'Positional argument tuple',
                                             'Dictionary',
                                             'Defaults'],
                                 'question': 'What does *args capture?'},
                                {'answer': '@wraps',
                                 'options': ['@wraps', '@cached', '@staticmethod', '@property'],
                                 'question': 'Which decorator preserves metadata when wrapping functions?'},
                                {'answer': 'Generator',
                                 'options': ['Coroutine', 'Generator', 'Lambda', 'Context manager'],
                                 'question': 'What does yield create?'},
                                {'answer': 'venv',
                                 'options': ['venv', 'pip', 'sys', 'pathlib'],
                                 'question': 'Which module manages virtual environments?'}],
                       'medium': [{'answer': 'while',
                                   'options': ['for', 'loop', 'while', 'repeat'],
                                   'question': 'Which loop runs while a condition remains True?'},
                                  {'answer': 'Removes last',
                                   'options': ['Skips first', 'Removes last', 'Reverses list', 'Duplicates list'],
                                   'question': 'What does slicing [:-1] do?'},
                                  {'answer': 'Building lists concisely',
                                   'options': ['Building lists concisely',
                                               'Designing classes',
                                               'Debugging',
                                               'Memory cleanup'],
                                   'question': 'List comprehension is useful for?'},
                                  {'answer': 'try',
                                   'options': ['catch', 'rescue', 'try', 'handle'],
                                   'question': 'Which keyword handles exceptions?'}]},
  'module_title': 'Python Foundations',
  'title': 'Python Foundations Quiz',
  'topic': 'Python'},
 {'description': 'SELECT/WHERE and aggregation fundamentals.',
  'difficulty_pools': {'easy': [{'answer': 'FROM',
                                 'options': ['SELECT', 'FROM', 'WHERE', 'GROUP'],
                                 'question': 'Which clause specifies the table to read from?'},
                                {'answer': 'DISTINCT',
                                 'options': ['UNIQUE', 'DISTINCT', 'FILTER', 'CLEAN'],
                                 'question': 'Which keyword removes duplicate rows?'},
                                {'answer': 'Filters rows',
                                 'options': ['Sorts rows', 'Filters rows', 'Creates columns', 'Counts rows'],
                                 'question': 'What does the WHERE clause do?'},
                                {'answer': 'COUNT',
                                 'options': ['SUM', 'AVG', 'COUNT', 'MIN'],
                                 'question': 'Which aggregate counts rows?'}],
                       'hard': [{'answer': 'Row existence in subquery',
                                 'options': ['Column existence',
                                             'Row existence in subquery',
                                             'Index usage',
                                             'Transaction state'],
                                 'question': 'What does EXISTS check for?'},
                                {'answer': 'ORDER BY',
                                 'options': ['SORT BY', 'ORDER BY', 'GROUP BY', 'ALIGN BY'],
                                 'question': 'Which clause enforces ordering?'},
                                {'answer': 'col AS alias',
                                 'options': ['col alias', 'col -> alias', 'col = alias', 'col AS alias'],
                                 'question': 'How do you alias a column?'},
                                {'answer': 'Read Committed',
                                 'options': ['Read Uncommitted', 'Read Committed', 'Chaos', 'Snapshot'],
                                 'question': 'Which isolation level prevents dirty reads?'}],
                       'medium': [{'answer': 'GROUP BY',
                                   'options': ['GROUP BY', 'ORDER BY', 'HAVING', 'LIMIT'],
                                   'question': 'Which clause groups rows before aggregation?'},
                                  {'answer': 'GROUP BY',
                                   'options': ['SELECT', 'WHERE', 'GROUP BY', 'FROM'],
                                   'question': 'HAVING is evaluated after which clause?'},
                                  {'answer': 'INNER',
                                   'options': ['LEFT', 'RIGHT', 'FULL', 'INNER'],
                                   'question': 'Which join returns only matching rows?'},
                                  {'answer': '10 and 20 inclusive',
                                   'options': ['10 only', '10 and 20 inclusive', '20 only', 'Exclusive'],
                                   'question': 'What does BETWEEN 10 AND 20 include?'}]},
  'module_title': 'SQL Basics',
  'title': 'SQL Basics Quiz',
  'topic': 'SQL'},
 {'description': 'Chart selection and storytelling.',
  'difficulty_pools': {'easy': [{'answer': 'Pie chart',
                                 'options': ['Histogram', 'Pie chart', 'Scatter', 'Box'],
                                 'question': 'Which plot shows parts of a whole?'},
                                {'answer': 'Matplotlib',
                                 'options': ['NumPy', 'Matplotlib', 'Pandas', 'TensorFlow'],
                                 'question': 'Base Python charting library?'},
                                {'answer': 'Histogram',
                                 'options': ['Line', 'Histogram', 'Heatmap', 'Pie'],
                                 'question': 'Which chart shows distribution over bins?'},
                                {'answer': 'Colorblind',
                                 'options': ['Random', 'Colorblind', 'Rainbow', 'Classic'],
                                 'question': 'Which palette avoids red-green issues?'}],
                       'hard': [{'answer': 'Treemap',
                                 'options': ['Scatter', 'Treemap', 'Pie', 'Line'],
                                 'question': 'Which chart shows hierarchical data best?'},
                                {'answer': 'Range spans orders of magnitude',
                                 'options': ['Never',
                                             'Range spans orders of magnitude',
                                             'For tiny datasets',
                                             'Night mode'],
                                 'question': 'When use log scales?'},
                                {'answer': 'Unnecessary clutter',
                                 'options': ['Useful labels', 'Unnecessary clutter', 'Legends', 'Axes'],
                                 'question': 'What is chart junk?'},
                                {'answer': 'Sankey',
                                 'options': ['Sankey', 'Box plot', 'Histogram', 'Violin'],
                                 'question': 'Which chart shows flow between categories?'}],
                       'medium': [{'answer': 'boxplot',
                                   'options': ['barplot', 'boxplot', 'violinplot', 'heatmap'],
                                   'question': 'Which Seaborn function shows categories vs numeric with boxes?'},
                                  {'answer': 'Matrix values',
                                   'options': ['Images', 'Matrix values', 'Audio', 'Video'],
                                   'question': 'What does a heatmap encode?'},
                                  {'answer': 'Highlight key values',
                                   'options': ['Decoration', 'Highlight key values', 'Increase size', 'Hide noise'],
                                   'question': 'Why annotate points?'},
                                  {'answer': 'Line chart',
                                   'options': ['Line chart', 'Pie chart', 'Tree map', 'Radar'],
                                   'question': 'Which chart shows trend over time best?'}]},
  'module_title': 'Data Visualization',
  'title': 'Data Visualization Quiz',
  'topic': 'Data Visualization'},
 {'description': 'Core concepts for cloud infrastructure.',
  'difficulty_pools': {'easy': [{'answer': 'Software as a Service',
                                 'options': ['Software as a Service',
                                             'Storage as a Service',
                                             'Security as a Service',
                                             'Server as a Service'],
                                 'question': 'What does SaaS stand for?'},
                                {'answer': 'IaaS',
                                 'options': ['IaaS', 'SaaS', 'PaaS', 'FaaS'],
                                 'question': 'Which model rents virtual machines?'},
                                {'answer': 'IaaS',
                                 'options': ['SaaS', 'IaaS', 'PaaS', 'On-prem'],
                                 'question': 'AWS EC2 is an example of?'},
                                {'answer': 'Amazon S3',
                                 'options': ['Amazon S3', 'Amazon EC2', 'AWS Lambda', 'Amazon RDS'],
                                 'question': 'Which service is object storage?'}],
                       'hard': [{'answer': 'Peak workloads via public cloud spillover',
                                 'options': ['Database migrations',
                                             'Peak workloads via public cloud spillover',
                                             'Billing',
                                             'DNS'],
                                 'question': 'Cloud bursting handles?'},
                                {'answer': 'EKS',
                                 'options': ['ECS', 'EKS', 'Fargate', 'Lightsail'],
                                 'question': 'Managed Kubernetes on AWS?'},
                                {'answer': 'Secure resource sharing',
                                 'options': ['Single tenant',
                                             'Secure resource sharing',
                                             'Only on-prem',
                                             'No virtualization'],
                                 'question': 'Multi-tenancy ensures?'},
                                {'answer': 'Large data transfers',
                                 'options': ['Serverless compute', 'Large data transfers', 'Cost reporting', 'Chat'],
                                 'question': 'Snowball is used for?'}],
                       'medium': [{'answer': 'Managed runtimes and tools',
                                   'options': ['Hardware only',
                                               'Full apps',
                                               'Managed runtimes and tools',
                                               'Networking gear'],
                                   'question': 'What does PaaS primarily provide?'},
                                  {'answer': 'Lambda',
                                   'options': ['EC2', 'Lambda', 'EBS', 'Route53'],
                                   'question': 'Which AWS service runs code serverlessly?'},
                                  {'answer': 'Isolated network',
                                   'options': ['Physical servers',
                                               'Isolated network',
                                               'Database backups',
                                               'User identities'],
                                   'question': 'A VPC provides what?'},
                                  {'answer': 'CloudFront',
                                   'options': ['CloudFront', 'RDS', 'SQS', 'Glue'],
                                   'question': 'Which service caches content globally?'}]},
  'module_title': 'Cloud Computing',
  'title': 'Cloud Computing Quiz',
  'topic': 'Cloud Computing'},
 {'description': 'JavaScript and front-end fundamentals.',
  'difficulty_pools': {'easy': [{'answer': 'HyperText Markup Language',
                                 'options': ['HyperText Markup Language',
                                             'HighText Markdown Language',
                                             'Hyperlink Markup Language',
                                             'Home Tool Markup Language'],
                                 'question': 'What does HTML stand for?'},
                                {'answer': '<script>',
                                 'options': ['<script>', '<style>', '<js>', '<code>'],
                                 'question': 'Which tag wraps JavaScript?'},
                                {'answer': 'Styling',
                                 'options': ['Structure', 'Behavior', 'Styling', 'Database'],
                                 'question': 'What does CSS control?'},
                                {'answer': '=',
                                 'options': ['=', '==', '===', ':='],
                                 'question': 'Which operator assigns a value?'}],
                       'hard': [{'answer': 'Function with lexical scope refs',
                                 'options': ['CSS trick',
                                             'Function with lexical scope refs',
                                             'Database transaction',
                                             'Loop construct'],
                                 'question': 'A closure is?'},
                                {'answer': 'Promises/async-await',
                                 'options': ['Event bubbling', 'Promises/async-await', 'Shadow DOM', 'Box model'],
                                 'question': 'Which pattern avoids callback hell?'},
                                {'answer': 'DOM diffing performance',
                                 'options': ['Network speed',
                                             'DOM diffing performance',
                                             'CSS specificity',
                                             'DB storage'],
                                 'question': 'Virtual DOM improves?'},
                                {'answer': 'Canvas API',
                                 'options': ['Canvas API', 'Fetch API', 'WebRTC', 'Service Worker'],
                                 'question': 'Which API draws 2D graphics?'}],
                       'medium': [{'answer': 'Document Object Model',
                                   'options': ['Document Object Model',
                                               'Data Orientation Map',
                                               'Dynamic Object Mechanism',
                                               'Design Object Model'],
                                   'question': 'DOM stands for?'},
                                  {'answer': 'push()',
                                   'options': ['shift()', 'unshift()', 'push()', 'pop()'],
                                   'question': 'Which array method adds to the end?'},
                                  {'answer': 'Common ancestor',
                                   'options': ['Each child', 'Common ancestor', 'Window', 'Random element'],
                                   'question': 'Event delegation handles events at?'},
                                  {'answer': 'useEffect',
                                   'options': ['useState', 'useEffect', 'useMemo', 'useReducer'],
                                   'question': 'Which hook replaces componentDidMount?'}]},
  'module_title': 'Web Design with JavaScript',
  'title': 'Web Design with JavaScript Quiz',
  'topic': 'Web Design with JavaScript'},
 {'description': 'Arrays, stacks, queues, trees.',
  'difficulty_pools': {'easy': [{'answer': 'Queue',
                                 'options': ['Stack', 'Queue', 'Tree', 'Graph'],
                                 'question': 'Which structure uses FIFO?'},
                                {'answer': 'Stack',
                                 'options': ['Array', 'Stack', 'Graph', 'Queue'],
                                 'question': 'Which uses LIFO?'},
                                {'answer': 'Hash map',
                                 'options': ['Array', 'Hash map', 'Stack', 'Queue'],
                                 'question': 'Which stores key-value pairs?'},
                                {'answer': 'Tree',
                                 'options': ['Stack', 'Queue', 'Tree', 'Array'],
                                 'question': 'Which structure is hierarchical?'}],
                       'hard': [{'answer': 'Approximate balance via rotations',
                                 'options': ['Exact balance',
                                             'Approximate balance via rotations',
                                             'Min-heap invariant',
                                             'Adjacency lists'],
                                 'question': 'Red-black tree maintains?'},
                                {'answer': 'O(E log V)',
                                 'options': ['O(E + V)', 'O(E log V)', 'O(V^2)', 'O(log V)'],
                                 'question': 'Dijkstra with binary heap complexity?'},
                                {'answer': 'Separate chaining',
                                 'options': ['Open addressing', 'Separate chaining', 'Double hashing', 'Quadratic'],
                                 'question': 'Which collision technique uses linked-list buckets?'},
                                {'answer': 'O(V^2)',
                                 'options': ['O(V)', 'O(E)', 'O(V^2)', 'O(log V)'],
                                 'question': 'Adjacency matrix space complexity?'}],
                       'medium': [{'answer': 'BFS',
                                   'options': ['DFS', 'BFS', 'In-order', 'Post-order'],
                                   'question': 'Which traversal visits level by level?'},
                                  {'answer': 'O(log n)',
                                   'options': ['O(n)', 'O(log n)', 'O(1)', 'O(n log n)'],
                                   'question': 'Binary search complexity on sorted array?'},
                                  {'answer': 'Stack',
                                   'options': ['Queue', 'Stack', 'Heap', 'Graph'],
                                   'question': 'Structure best for recursion tracking?'},
                                  {'answer': 'Priority queue',
                                   'options': ['Hash table', 'Priority queue', 'Linked list', 'Array'],
                                   'question': 'Which structure suits priority scheduling?'}]},
  'module_title': 'Data Structures',
  'title': 'Data Structures Quiz',
  'topic': 'Data Structures'},
 {'description': 'Neural networks and training concepts.',
  'difficulty_pools': {'easy': [{'answer': 'Sigmoid',
                                 'options': ['ReLU', 'Sigmoid', 'Linear', 'Softmax'],
                                 'question': 'Which activation outputs values between 0 and 1?'},
                                {'answer': 'Graphics Processing Unit',
                                 'options': ['General Processing Unit',
                                             'Graphics Processing Unit',
                                             'Graph Programming Utility',
                                             'Global Processing Unit'],
                                 'question': 'What does GPU stand for?'},
                                {'answer': 'Neuron',
                                 'options': ['Layer', 'Neuron', 'Batch', 'Epoch'],
                                 'question': 'Basic unit in a neural network?'},
                                {'answer': 'Measure model error',
                                 'options': ['Measure model error',
                                             'Store data',
                                             'Visualize layers',
                                             'Compress inputs'],
                                 'question': 'Purpose of a loss function?'}],
                       'hard': [{'answer': 'Focus on relevant input',
                                 'options': ['Ignore context',
                                             'Focus on relevant input',
                                             'Remove positional encoding',
                                             'Train without gradients'],
                                 'question': 'Attention mechanism allows models to?'},
                                {'answer': 'Transformer',
                                 'options': ['CNN', 'Transformer', 'RNN', 'GAN'],
                                 'question': 'Which architecture relies fully on attention?'},
                                {'answer': 'Gradients shrink to zero',
                                 'options': ['Gradients explode',
                                             'Gradients shrink to zero',
                                             'Weights explode',
                                             'Batch sizes vanish'],
                                 'question': 'Vanishing gradient problem means?'},
                                {'answer': 'Generator/discriminator',
                                 'options': ['Autoencoder/decoder',
                                             'Generator/discriminator',
                                             'Encoder/classifier',
                                             'Critic/transformer'],
                                 'question': 'GAN training optimizes?'}],
                       'medium': [{'answer': 'Gradients of loss w.r.t weights',
                                   'options': ['Forward pass',
                                               'Gradients of loss w.r.t weights',
                                               'Batch size',
                                               'Activation outputs'],
                                   'question': 'Backpropagation computes?'},
                                  {'answer': 'Reduce overfitting',
                                   'options': ['Reduce overfitting',
                                               'Store parameters',
                                               'Normalize batches',
                                               'Speed up inference'],
                                   'question': 'Dropout helps?'},
                                  {'answer': 'Convolutional',
                                   'options': ['Fully connected', 'Convolutional', 'Recurrent', 'Embedding'],
                                   'question': 'Key layer for spatial features in CNNs?'},
                                  {'answer': 'Stabilizes training',
                                   'options': ['Stabilizes training',
                                               'Saves memory',
                                               'Replaces dropout',
                                               'Reduces dataset'],
                                   'question': 'Batch normalization benefit?'}]},
  'module_title': 'Deep Learning Basics',
  'title': 'Deep Learning Basics Quiz',
  'topic': 'Deep Learning'},
 {'description': 'CI/CD, automation, and monitoring basics.',
  'difficulty_pools': {'easy': [{'answer': 'Continuous Integration',
                                 'options': ['Continuous Inspection',
                                             'Continuous Integration',
                                             'Continuous Invention',
                                             'Continuous Improvement'],
                                 'question': 'What does CI stand for?'},
                                {'answer': 'Terraform',
                                 'options': ['Terraform', 'Photoshop', 'Excel', 'PowerPoint'],
                                 'question': 'Which tool automates infrastructure as code?'},
                                {'answer': 'Containerization',
                                 'options': ['Containerization', 'Unit testing', 'UI design', 'Manual deploys'],
                                 'question': 'What is Docker used for?'},
                                {'answer': 'Grafana',
                                 'options': ['Grafana', 'Git', 'Slack', 'Sheets'],
                                 'question': 'Which service monitors logs?'}],
                       'hard': [{'answer': 'Mean Time To Recovery',
                                 'options': ['Mean Time To Recovery',
                                             'Most Tickets To Resolve',
                                             'Minimum Test Ratio',
                                             'Managed Team Retention'],
                                 'question': 'MTTR stands for?'},
                                {'answer': 'Canary',
                                 'options': ['Big bang', 'Canary', 'Freeze', 'Shadow'],
                                 'question': 'Which deployment gradually shifts traffic?'},
                                {'answer': 'Traces',
                                 'options': ['Screenshots', 'Traces', 'Dashboards', 'Emails'],
                                 'question': 'Observability pillars include logs, metrics, and?'},
                                {'answer': 'Deployments via chat tools',
                                 'options': ['Chat-based support',
                                             'Deployments via chat tools',
                                             'New IDE',
                                             'Random releases'],
                                 'question': 'ChatOps refers to?'}],
                       'medium': [{'answer': 'Parallel old/new versions',
                                   'options': ['Two teams', 'Parallel old/new versions', 'Design doc', 'DB sharding'],
                                   'question': 'What is blue/green deployment?'},
                                  {'answer': 'Kubernetes',
                                   'options': ['Kubernetes', 'Photoshop', 'Excel', 'Figma'],
                                   'question': 'Tool orchestrating containers?'},
                                  {'answer': 'Automated build/test/deploy workflow',
                                   'options': ['Server rack',
                                               'Automated build/test/deploy workflow',
                                               'Checklist',
                                               'Network interface'],
                                   'question': 'A pipeline represents?'},
                                  {'answer': 'Version-controlled definitions',
                                   'options': ['Manual changes',
                                               'Version-controlled definitions',
                                               'More spreadsheets',
                                               'Fewer releases'],
                                   'question': 'Infrastructure as Code benefits?'}]},
  'module_title': 'DevOps Fundamentals',
  'title': 'DevOps Fundamentals Quiz',
  'topic': 'DevOps'},
 {'description': 'Regression and classification fundamentals.',
  'difficulty_pools': {'easy': [{'answer': 'Labeled data',
                                 'options': ['Unlabeled data', 'Labeled data', 'No data', 'Random noise'],
                                 'question': 'Supervised learning uses?'},
                                {'answer': 'Logistic regression',
                                 'options': ['Linear regression', 'Logistic regression', 'K-means', 'Apriori'],
                                 'question': 'Which algorithm handles classification?'},
                                {'answer': 'Model memorizes training data but fails on new data',
                                 'options': ['Model generalizes perfectly',
                                             'Model memorizes training data but fails on new data',
                                             'Model never trains',
                                             'Model is too simple'],
                                 'question': 'What is overfitting?'},
                                {'answer': 'Train/test split',
                                 'options': ['Train/test split', 'Hash split', 'Sort split', 'ID split'],
                                 'question': 'Which split is used for validation?'}],
                       'hard': [{'answer': 'Subtracting gradient scaled by learning rate',
                                 'options': ['Adding gradient',
                                             'Subtracting gradient scaled by learning rate',
                                             'Random guessing',
                                             'Matrix inversion'],
                                 'question': 'Gradient descent updates weights by?'},
                                {'answer': 'Model complexity vs generalization',
                                 'options': ['CPU vs GPU',
                                             'Model complexity vs generalization',
                                             'Data vs code',
                                             'Loss vs accuracy'],
                                 'question': 'Bias-variance tradeoff balances?'},
                                {'answer': 'PCA',
                                 'options': ['PCA', 'Random forests', 'Bagging', 'Cross entropy'],
                                 'question': 'Which method reduces dimensionality?'},
                                {'answer': 'Different models via meta-learner',
                                 'options': ['Same model repeatedly',
                                             'Different models via meta-learner',
                                             'Only trees',
                                             'Hyperparameters'],
                                 'question': 'Stacking ensemble combines?'}],
                       'medium': [{'answer': 'Reduce overfitting',
                                   'options': ['Increase variance', 'Reduce overfitting', 'Stop training', 'Add noise'],
                                   'question': 'Regularization helps?'},
                                  {'answer': 'Precision/Recall or F1',
                                   'options': ['Accuracy only', 'Precision/Recall or F1', 'FPS', 'Entropy'],
                                   'question': 'Which metric suits imbalanced classification?'},
                                  {'answer': 'Number of clusters K',
                                   'options': ['Distance metric', 'Number of clusters K', 'Learning rate', 'Kernel'],
                                   'question': 'K-means requires choosing?'},
                                  {'answer': 'Standardization',
                                   'options': ['Standardization', 'One-hot', 'Hashing', 'Sampling'],
                                   'question': 'Which technique scales features to zero mean?'}]},
  'module_title': 'Machine Learning Intro',
  'title': 'Machine Learning Intro Quiz',
  'topic': 'Machine Learning'},
 {'description': 'Components, props, hooks, and state management.',
  'difficulty_pools': {'easy': [{'answer': 'JSX',
                                 'options': ['HTML strings', 'JSX', 'DB records', 'CSS'],
                                 'question': 'React components return?'},
                                {'answer': 'useState',
                                 'options': ['useState', 'useEffect', 'useMemo', 'useRef'],
                                 'question': 'Which hook manages component state?'},
                                {'answer': 'Immutable inputs',
                                 'options': ['Mutable state', 'Immutable inputs', 'CSS classes', 'Redux actions'],
                                 'question': 'Props are?'},
                                {'answer': 'create-react-app',
                                 'options': ['create-react-app', 'npm start', 'yarn add', 'vite'],
                                 'question': 'Which CLI bootstraps React apps?'}],
                       'hard': [{'answer': 'Functions',
                                 'options': ['Values', 'Functions', 'DOM nodes', 'Events'],
                                 'question': 'useCallback memoizes?'},
                                {'answer': 'Prevents re-render unless props change',
                                 'options': ['Always re-renders',
                                             'Prevents re-render unless props change',
                                             'Optimizes CSS',
                                             'Handles routing'],
                                 'question': 'React.memo does what?'},
                                {'answer': 'Container/presentational',
                                 'options': ['Container/presentational', 'MVC', 'Flux', 'Atomic'],
                                 'question': 'Which pattern splits components by responsibility?'},
                                {'answer': 'Handling loading states',
                                 'options': ['Handling loading states', 'Error logging', 'Routing', 'Styling'],
                                 'question': 'Suspense is used for?'}],
                       'medium': [{'answer': 'After render when dependencies change',
                                   'options': ['Only once',
                                               'After render when dependencies change',
                                               'Before render',
                                               'Never'],
                                   'question': 'useEffect runs when?'},
                                  {'answer': 'Efficient diffing',
                                   'options': ['Styling', 'Efficient diffing', 'State management', 'Routing'],
                                   'question': 'Keys in lists help with?'},
                                  {'answer': 'useRef',
                                   'options': ['useMemo', 'useRef', 'useReducer', 'useLayoutEffect'],
                                   'question': 'Which hook stores mutable values without re-rendering?'},
                                  {'answer': 'Prop drilling',
                                   'options': ['State', 'Prop drilling', 'Hooks', 'CSS'],
                                   'question': 'Context helps avoid?'}]},
  'module_title': 'React Essentials',
  'title': 'React Essentials Quiz',
  'topic': 'React'}]